### PR TITLE
MOABB notebook

### PR DESCRIPTION
**Pull request by sylvchev**
J'ai ajouté un repetoire notebook dans lequel j'ai mis ma proposition. Le notebook est quasi-terminé. Je dois juste lancer une grosse évaluation sur tous les datasets pour faire une comparaison.

### CODE REVIEW

**Comment by lkorczowski** [comment]
Should we give INSTALLATION instructions in README.md?

We should assume that researchers may have never used python before (e.g. Matlab users)

**Comment by sylvchev** [comment]
> Should we give INSTALLATION instructions in README.md?
> 
> We should assume that researchers may have never used python before (e.g. Matlab users)

I agree that it was the initial plan to make a real hands on session, asking people to follow and to reproduce code. With only 10 minutes for each code presentation, it is no longer possible. Furthermore, it is possible to ask people to install specific software on their computer but it should be advertise early. 

In my opinion, it is not necessary to give installation instruction in the README.md. The notebooks could explain how to install the libs to execute the code locally.

For the Matlab point, my opinion goes along the same line: we don't have the time to make an introduction to python. We could assume that people will work their way across the code, especially if we make some literate programming with the notebooks.

**Comment by sylvchev** [comment]
<p>Yes, I stopped the ongoing results. I have launched this large evaluation on a server.</p>

---

 <a href='https://app.reviewnb.com/lkorczowski/BCI-2021-Riemannian-Geometry-workshop/pull/2/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sylvchev** [comment]
<p>It will be generated at the end of the big evaluation.</p>

---

 <a href='https://app.reviewnb.com/lkorczowski/BCI-2021-Riemannian-Geometry-workshop/pull/2/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sylvchev** [comment]
Ready to merge!

**Pull request merged**
